n = -5:5;
delta = [zeros(1,5), 1, zeros(1,5)];
subplot(3,1,1);
stem(n, delta);
title('Unit Sample Sequence (\delta[n])');
xlabel('n');
ylabel('\delta[n]');
n = -5:5;
step = (n >= 0);
subplot(3,1,2);
stem(n, step);
title('Unit Step Signal (u[n])');
xlabel('n');
ylabel('u[n]');
n = 0:10;
ramp = n;
subplot(3,1,3);
stem(n, ramp);
title('Unit Ramp Signal (ramp[n])');
xlabel('n');
ylabel('ramp[n]');